### ISSUE TITLE
bug(log): TypeError when using msgspec in JSONRenderer 

### ISSUE THREAD

**Issue by gazorby** [topsport-com-au/starlite-saqlalchemy#166]
## Description

`msgspec.json.encode` does not seems to play well with strutclog's `JSONRenderer`:

```python
Traceback (most recent call last):
  File "/home/gazorby/.cache/pypoetry/virtualenvs/starlite-dev-MVX66ndR-py3.10/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/gazorby/.cache/pypoetry/virtualenvs/starlite-dev-MVX66ndR-py3.10/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/gazorby/.cache/pypoetry/virtualenvs/starlite-dev-MVX66ndR-py3.10/lib/python3.10/site-packages/starlite/app.py", line 410, in __call__
    await self.asgi_handler(scope, receive, self._wrap_send(send=send, scope=scope))  # type: ignore[arg-type]
  File "/home/gazorby/.cache/pypoetry/virtualenvs/starlite-dev-MVX66ndR-py3.10/lib/python3.10/site-packages/starlite/middleware/exceptions/middleware.py", line 58, in __call__
    await response(scope=scope, receive=receive, send=send)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/gazorby/.cache/pypoetry/virtualenvs/starlite-dev-MVX66ndR-py3.10/lib/python3.10/site-packages/structlog/_log_levels.py", line 200, in <lambda>
    lambda: ctx.run(lambda: self._proxy_to_logger(name, event, **kw)),
  File "/home/gazorby/.cache/pypoetry/virtualenvs/starlite-dev-MVX66ndR-py3.10/lib/python3.10/site-packages/structlog/_log_levels.py", line 200, in <lambda>
    lambda: ctx.run(lambda: self._proxy_to_logger(name, event, **kw)),
  File "/home/gazorby/.cache/pypoetry/virtualenvs/starlite-dev-MVX66ndR-py3.10/lib/python3.10/site-packages/structlog/_base.py", line 205, in _proxy_to_logger
    args, kw = self._process_event(method_name, event, event_kw)
  File "/home/gazorby/.cache/pypoetry/virtualenvs/starlite-dev-MVX66ndR-py3.10/lib/python3.10/site-packages/structlog/_base.py", line 162, in _process_event
    event_dict = proc(self._logger, method_name, event_dict)
  File "/home/gazorby/.cache/pypoetry/virtualenvs/starlite-dev-MVX66ndR-py3.10/lib/python3.10/site-packages/structlog/processors.py", line 328, in __call__
    return self._dumps(event_dict, **self._dumps_kw)
TypeError: Extra keyword arguments provided
```

## Steps to reproduce

Here is a minimal reproductible example:

```python
import msgspec
import structlog
from starlite import Controller, Starlite, get
from starlite_saqlalchemy import ConfigureApp, PluginConfig


class BuggyController(Controller):
    path: str = "/graphql"

    @get()
    async def handle_get(self) -> str:
        return "Hello World"


starlite_saqlalchemy_config = PluginConfig(do_worker=False, do_sentry=False)

# Enforce JSONRenderer
starlite_saqlalchemy_config.log_processors = [
    structlog.processors.JSONRenderer(serializer=msgspec.json.encode)
]

app = Starlite(
    route_handlers=[BuggyController],
    on_app_init=[ConfigureApp(config=starlite_saqlalchemy_config)],
)
```

A GET request to `/graphql` causes the above error

**Comment by gazorby** [comment]
No problem, take some rest!
